apiVersion: apps/v1
kind: Deployment
metadata:
    name: kn08-buysell
    namespace: kn08
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kn08-buysell
    template:
        metadata:
            labels:
                app: kn08-buysell
        spec:
            containers:
                - name: kn08-buysell
                  image: sxnic/kn08-buysell:v2
                  ports:
                      - containerPort: 8002
                  env:
                      - name: PORT
                        value: "8002"
                      - name: ACCOUNT_SERVICE_URL
                        value: "http://kn08-account.kn08.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
    name: kn08-buysell
    namespace: kn08
spec:
    selector:
        app: kn08-buysell
    ports:
        - protocol: TCP
          port: 8002
          targetPort: 8002