name: kn08

services:
  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - app
    depends_on:
      - account
      - buysell
      - sendreceive
  sendreceive:
    container_name: sendreceiveservice
    build:
      context: ./send-receive
      dockerfile: Dockerfile
    env_file:
      - ./send-receive/.env
    ports:
      - 8003:8003
    networks:
      - app
    depends_on:
      - account
  buysell:
    container_name: buysellservice
    build:
      context: ./buy-sell
      dockerfile: Dockerfile
    env_file:
      - ./buy-sell/.env
    ports:
      - 8002:8002
    networks:
      - app
    depends_on:
      - account
  account:
    container_name: account
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app
      - backbone
    depends_on:
      - database
  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=tbzPass123
    ports:
      - 3306:3306
    networks:
      backbone:
        ipv4_address: 172.31.0.10
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
    driver: local

networks:
  backbone:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/20
          ip_range: 172.31.0.0/24
          gateway: 172.31.0.254
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.16.0/20
          ip_range: 172.31.16.0/24
          gateway: 172.31.16.254