name: kn08

services:
  frontend:
    container_name: frontend-app
    image: sxnic/kn08-frontend:v1
    ports:
      - 80:3000
    networks:
      - app
    depends_on:
      - account
      - buysell
      - sendreceive
  sendreceive:
    container_name: sendreceiveservice
    image: sxnic/kn08-sendreceive:v2
    ports:
      - 8003:8003
    networks:
      - app
    depends_on:
      - account
  buysell:
    container_name: buysellservice
    image: sxnic/kn08-buysell:v2
    ports:
      - 8002:8002
    networks:
      - app
    depends_on:
      - account
  account:
    container_name: account
    image: sxnic/kn08-account:v2
    ports:
      - 8080:8080
    networks:
      - app
networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.16.0/20
          ip_range: 172.31.16.0/24
          gateway: 172.31.16.254