spring:
  application:
    name: api
  profiles:
    default: application-dev
    active: ${ACTIVE_PROFILE:application-dev}
  config:
    import: file:./${ACTIVE_PROFILE}.yml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USER}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/public/
  main:
    banner-mode: off
server:
  address: ${ADDRESS:localhost}
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html, text/xml, application/json
    min-response-size: 1024
logging:
  level:
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %yellow(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %yellow(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
  file:
    name: src/main/resources/logs/${ACTIVE_PROFILE}.log
supabase:
  url: ${SUPABASE_URL}
  anon: ${SUPABASE_ANON_KEY}
  secret: ${SUPABASE_JWT_SECRET}