spring:
  application:
    name: api
  profiles:
    default: application-dev
    active: application-dev
  config:
    import: classpath:/application-dev.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?user=postgres.sjvxavqmxiqqjhbevncn&password=oRhOIWAot3rfisH3
    username: postgres.sjvxavqmxiqqjhbevncn
    password: oRhOIWAot3rfisH3
    driverClassName: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/public/
server:
  port: 9000
  compression:
    enabled: true
    mime-types: text/html, text/xml, application/json
    min-response-size: 1024
logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %green(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %yellow(%logger{40}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
  file:
    name: classpath:/logs/application-dev.log
supabase:
  url: https://sjvxavqmxiqqjhbevncn.supabase.co
  anon: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqdnhhdnFteGlxcWpoYmV2bmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MTE1NjEsImV4cCI6MjA1MjA4NzU2MX0.OCnoACz0VWXPNEkNI6nk8JbDLtr2zq3CSA7Y-bKDYFk # ${SUPABASE_ANON_KEY}
  secret: TheUhZJOxhx21hCK2nh5Nk8LIxYUYK1efrDCXn2v8ot7rblTikqFfbvfl1it+W3tB0oMYc7FWEsr8QO1oQc5yA==