spring:
  config:
    activate:
      on-profile: application-dev
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-path: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true