#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5J5spKO9mDVPnH1RQEhf09XqmoFLqrHUURRZiG3qn+R0eRPfB9D6m4Y7CK6MhKj+TZzp5vCMOI6OMYRNz3LH25J9SQ/cEY6KVf/R4dd5eELRGuFCEGV+zhdu49bC6bLe5oYHBT9855Np+Q+T5GEGa9lM/PGWhll4HTY4IF+oG1TUlXvbLTPCQlVn/HHmm00MeQ0qpyFPntx939JHsM689PDtCs+Uq6AeYklLqBIpeqHtXRT0HPJGJUAY1UJE64B0pW7F/+bx2uwEuVnkGGSIWcbK+jZrj8fBjq8eflepaD4xMFlL30MkzwdpC0o3yOHOfYjLEDZW+fEur5afQBtz47p0nBO56SNQ0o/x6FK2LdzNn0cfrvRG7fHNoLRO4wL9eTwfXEDt5A43jTpS0RY45N4qWE4ap1LOM5Lrx9ZF4CUIHP94omkVwy00MCtHURpDXP8hwyFzY5w5qNt1uKxPEyuteTe+XE6pDG4tPNvFIZKrMPc6chbyPwjTsfN3+l2bGM2P7roXP30uD7PmqIZJHTytUffkHv6HmNmD4HZo+8DWnjfknsTotiN0JHRjcuEJVW4bgpA9iW1YFQqpvbem1rHHi137AJTT8EjvcGbrZfP1IjHRqEO/cx6vVKPgxWi9sUYVtZm4fpYTUEQSaSkPdzyjigYJs5gyH0FiiU7ZX3Q== sxnic@sxnic
groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
