name: m347-kn04a

services:
  web:
    container_name: m347-kn04a-web
    build:
      context: .
      dockerfile: .docker/web.Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - kn04a-net
  db:
    container_name: m347-kn04a-db
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=tbzPass123
    ports:
      - 3306:3306
    networks:
      - kn04a-net
    volumes:
      - db_data:/var/lib/mysql

networks:
  kn04a-net:
    driver: bridge

volumes:
  db_data:
    driver: local